package ventanas;

import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MAPA
 */
public class CargarProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalCargar
     */
     
    public CargarProducto(JDesktopPane desktopPane)
    {
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);  
	this.setBorder(new EmptyBorder(0, 0, 0, 0));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxProveedor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxPresentacion = new javax.swing.JComboBox<>();
        jTextFieldNombreProveedor = new javax.swing.JTextField();
        jTextFieldPrecioVenta = new javax.swing.JTextField();
        jTextFieldCosto = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldIDEmpresa = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextFieldTipo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldDinero = new javax.swing.JTextField();
        jTextFieldCambio = new javax.swing.JTextField();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldPrecioCliente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jTextFieldTipo1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("CARGAR PRODUCTOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(650, 10, 260, 30);

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Precio Clientes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 410, 120, 17);

        jComboBoxProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Añadir" }));
        jComboBoxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProveedor);
        jComboBoxProveedor.setBounds(140, 20, 170, 20);

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Fecha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 20, 60, 20);

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Descripción");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 440, 110, 17);

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Tipo Producto");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 110, 110, 17);

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Marca");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 200, 90, 17);

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("ID Producto");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 80, 100, 17);

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Cantidad");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 300, 90, 17);

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Costo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 340, 90, 17);

        jButtonAceptar.setText("Realizar compra");
        jButtonAceptar.setEnabled(false);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar);
        jButtonAceptar.setBounds(820, 480, 140, 40);

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirNegro.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(670, 480, 140, 40);

        jComboBoxPresentacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Otros..." }));
        jComboBoxPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPresentacionActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPresentacion);
        jComboBoxPresentacion.setBounds(140, 240, 170, 20);

        jTextFieldNombreProveedor.setEditable(false);
        jTextFieldNombreProveedor.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldNombreProveedor.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(jTextFieldNombreProveedor);
        jTextFieldNombreProveedor.setBounds(140, 50, 170, 21);

        jTextFieldPrecioVenta.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldPrecioVenta.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioVentaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldPrecioVenta);
        jTextFieldPrecioVenta.setBounds(140, 370, 170, 21);

        jTextFieldCosto.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldCosto.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCostoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCosto);
        jTextFieldCosto.setBounds(140, 330, 170, 21);

        jTextFieldCantidad.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldCantidad.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCantidad);
        jTextFieldCantidad.setBounds(140, 300, 170, 21);

        jTextFieldNombre.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(jTextFieldNombre);
        jTextFieldNombre.setBounds(140, 170, 170, 21);

        jTextFieldIDEmpresa.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldIDEmpresa.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldIDEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDEmpresaActionPerformed(evt);
            }
        });
        jTextFieldIDEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDEmpresaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldIDEmpresa);
        jTextFieldIDEmpresa.setBounds(140, 80, 170, 21);

        jTextFieldFecha.setEditable(false);
        jTextFieldFecha.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldFecha.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(jTextFieldFecha);
        jTextFieldFecha.setBounds(400, 20, 170, 21);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirNegro.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(920, 10, 40, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Tipo", "Codigo", "Marca", "Cant", "Costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 120, 630, 350);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 51, 51));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 460, 310, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregarr.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 480, 150, 40);

        jTextFieldTipo.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldTipo.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldTipo.setToolTipText("");
        jTextFieldTipo.setEnabled(false);
        jTextFieldTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTipo);
        jTextFieldTipo.setBounds(140, 270, 170, 21);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jTextFieldDinero.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldDinero.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldDinero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDineroKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldDinero);
        jTextFieldDinero.setBounds(10, 30, 90, 21);

        jTextFieldCambio.setEditable(false);
        jTextFieldCambio.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldCambio.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jTextFieldCambio);
        jTextFieldCambio.setBounds(110, 30, 100, 21);

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldTotal.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jTextFieldTotal);
        jTextFieldTotal.setBounds(220, 30, 100, 21);

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(220, 0, 60, 30);

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cambio");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(110, 0, 70, 30);

        jLabel14.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Monto");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 0, 60, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(340, 50, 380, 60);

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Proveedor");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 20, 110, 17);

        jLabel15.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("Precio de Venta");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 370, 120, 17);

        jTextFieldPrecioCliente.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldPrecioCliente.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldPrecioCliente.setName(""); // NOI18N
        jTextFieldPrecioCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioClienteKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldPrecioCliente);
        jTextFieldPrecioCliente.setBounds(140, 400, 170, 21);

        jLabel16.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setText("Presentacion");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 240, 110, 17);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Otros..." }));
        jComboBoxTipo.setName(""); // NOI18N
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipo);
        jComboBoxTipo.setBounds(140, 110, 170, 20);

        jTextFieldTipo1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldTipo1.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldTipo1.setToolTipText("");
        jTextFieldTipo1.setEnabled(false);
        jTextFieldTipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTipo1);
        jTextFieldTipo1.setBounds(140, 140, 170, 21);

        jLabel17.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("código");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 170, 90, 17);

        jTextFieldMarca.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTextFieldMarca.setForeground(new java.awt.Color(0, 51, 51));
        jTextFieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMarca);
        jTextFieldMarca.setBounds(140, 200, 170, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
    
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jComboBoxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProveedorActionPerformed
        
    }//GEN-LAST:event_jComboBoxProveedorActionPerformed

    private void jTextFieldTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoActionPerformed

    private void jComboBoxPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPresentacionActionPerformed
        
    }//GEN-LAST:event_jComboBoxPresentacionActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldDineroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDineroKeyTyped
        char c = evt.getKeyChar();			
        if(c<'0'||c>'9')
            if(evt.getKeyChar() != '.')
                evt.consume();
    }//GEN-LAST:event_jTextFieldDineroKeyTyped

    private void jTextFieldCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadKeyTyped
        char c = evt.getKeyChar();			
        if(c<'0'||c>'9')                  
            evt.consume();
    }//GEN-LAST:event_jTextFieldCantidadKeyTyped

    private void jTextFieldCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostoKeyTyped
        char c = evt.getKeyChar();			
        if(c<'0'||c>'9')
        {
            if(evt.getKeyChar() != '.')
                evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCostoKeyTyped

    private void jTextFieldPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioVentaKeyTyped
        char c = evt.getKeyChar();			
        if(c<'0'||c>'9')                  
            if(evt.getKeyChar() != '.')
                evt.consume();
    }//GEN-LAST:event_jTextFieldPrecioVentaKeyTyped

    private void jTextFieldIDEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDEmpresaKeyTyped
        char c = evt.getKeyChar();			
        if(c<'0'||c>'9')                  
            evt.consume();
    }//GEN-LAST:event_jTextFieldIDEmpresaKeyTyped

    private void jTextFieldPrecioVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioVentaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioVentaKeyReleased

    private void jTextFieldIDEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDEmpresaActionPerformed

    private void jTextFieldPrecioClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioClienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioClienteKeyReleased

    private void jTextFieldPrecioClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioClienteKeyTyped

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jTextFieldTipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipo1ActionPerformed

    private void jTextFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMarcaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxPresentacion;
    private javax.swing.JComboBox<String> jComboBoxProveedor;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldCambio;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldCosto;
    private javax.swing.JTextField jTextFieldDinero;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldIDEmpresa;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreProveedor;
    private javax.swing.JTextField jTextFieldPrecioCliente;
    private javax.swing.JTextField jTextFieldPrecioVenta;
    private javax.swing.JTextField jTextFieldTipo;
    private javax.swing.JTextField jTextFieldTipo1;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
