package ventanas;
import Atxy2k.CustomTextField.RestrictedTextField;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class CargarClientes extends javax.swing.JInternalFrame {

    public CargarClientes() {
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);  
	this.setBorder(new EmptyBorder(0, 0, 0, 0));
        initComponents();
        RestrictedTextField r = new RestrictedTextField(txtTelefono);
        r.setLimit(8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtNIT = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        LblCerrar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("CREAR CLIENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(278, 20, 210, 30);

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Telefono");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(238, 280, 90, 17);

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("NIT");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(238, 150, 70, 17);

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("Nombre");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(238, 100, 80, 17);

        txtTelefono.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 51, 51));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(328, 280, 120, 25);

        txtNIT.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtNIT.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(txtNIT);
        txtNIT.setBounds(330, 140, 120, 25);

        txtNombre.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(txtNombre);
        txtNombre.setBounds(328, 100, 200, 25);

        btnGuardar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 51, 51));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(238, 330, 150, 40);

        jButtonCancelar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(0, 51, 51));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirNegro.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(398, 330, 150, 40);

        LblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirNegro.png"))); // NOI18N
        LblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(LblCerrar);
        LblCerrar.setBounds(740, 10, 40, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_LblCerrarMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        txtNombre.setText("");
        txtNIT.setText("");
        txtTelefono.setText("");
        txtNombre.requestFocus();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();			
        if(c<'0'||c>'9')                  
            evt.consume();
    }//GEN-LAST:event_txtTelefonoKeyTyped


    public void SetDesktopPane(JDesktopPane mipanel,boolean indicador)
    {
        this.mipanel=mipanel;
        this.indicador=indicador;
    }
    
    private boolean indicador=false;
    private JDesktopPane mipanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
