/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MAPA
 */
public class Compras extends javax.swing.JInternalFrame {

    /**
     * Creates new form Compras
     */
    private DefaultTableModel model;
    public Compras() {
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);  
	this.setBorder(new EmptyBorder(0, 0, 0, 0));
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBuscarCliente = new javax.swing.JTextField();
        btnDetalleCompra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblCerrar5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Compra", "fecha de Compra", "ID Proveedor", "Proveedor", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 930, 370);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("VER COMPRAS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(650, 10, 230, 40);

        jTextFieldBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarClienteActionPerformed(evt);
            }
        });
        jTextFieldBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarClienteKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldBuscarCliente);
        jTextFieldBuscarCliente.setBounds(150, 20, 190, 20);

        btnDetalleCompra.setText("Detalle compras");
        getContentPane().add(btnDetalleCompra);
        btnDetalleCompra.setBounds(20, 50, 109, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Buscar por nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 116, 30);

        lblCerrar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirNegro.png"))); // NOI18N
        lblCerrar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar5MouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrar5);
        lblCerrar5.setBounds(890, 10, 33, 39);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarClienteActionPerformed

    private void jTextFieldBuscarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarClienteKeyPressed
        
    }//GEN-LAST:event_jTextFieldBuscarClienteKeyPressed

    private void lblCerrar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar5MouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCerrar5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalleCompra;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBuscarCliente;
    private javax.swing.JLabel lblCerrar5;
    // End of variables declaration//GEN-END:variables
}