/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author MAPA
 */
public class DetalleCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form DetalleCompra
     */
    public DetalleCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jTextFieldFechaVenta = new javax.swing.JTextField();
        jTextFieldTotalVenta = new javax.swing.JTextField();
        jTextFieldVendedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lblCerrar5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(710, 450));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("DETALLE DE COMPRA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(630, 10, 260, 30);

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("Buscar por ID Compra");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 20, 180, 17);

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("Fecha de compra");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 90, 130, 17);

        jLabel14.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("Total Total");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(340, 60, 110, 17);

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("Vendedor:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(340, 90, 110, 17);
        getContentPane().add(jTextFieldNombreCliente);
        jTextFieldNombreCliente.setBounds(160, 60, 160, 20);
        getContentPane().add(jTextFieldFechaVenta);
        jTextFieldFechaVenta.setBounds(160, 90, 160, 20);
        getContentPane().add(jTextFieldTotalVenta);
        jTextFieldTotalVenta.setBounds(430, 60, 160, 20);
        getContentPane().add(jTextFieldVendedor);
        jTextFieldVendedor.setBounds(430, 90, 160, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Compra", "Cantidad", "Tipo Producto", "Codigo", "Marca", "Presentacion", "Cantidad", "Costo Unidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 930, 360);

        jButton1.setText("ACEPTAR");
        getContentPane().add(jButton1);
        jButton1.setBounds(800, 500, 90, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(190, 20, 210, 20);

        jLabel15.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("Nombre Proveedor");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 60, 130, 17);

        lblCerrar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirNegro.png"))); // NOI18N
        getContentPane().add(lblCerrar5);
        lblCerrar5.setBounds(900, 10, 33, 39);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldFechaVenta;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldTotalVenta;
    private javax.swing.JTextField jTextFieldVendedor;
    private javax.swing.JLabel lblCerrar5;
    // End of variables declaration//GEN-END:variables
}
